title: minimaliz.me
description: Une plateforme épurée, où la simplicité du minimalisme rencontre l'innovation des technologies Apple. Un espace dédié à l'exploration des horizons numériques et à l'évolution personnelle.
plugins:
  - jekyll-feed
  
